# Generated by Django 5.2.6 on 2025-10-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapel',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='chapel',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True),
        ),
    ]
