# Generated by Django 5.2.6 on 2025-10-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapels', '0002_alter_chapel_latitude_alter_chapel_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapel',
            old_name='address',
            new_name='street',
        ),
        migrations.AddField(
            model_name='chapel',
            name='celebrant_group',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='chapel',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
